# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Digital-Clock with React-App

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./digital-clock-with-React

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Check directory
        run: ls -a
      - name: solve opensslErrorStack issue
        run: export NODE_OPTIONS=--openssl-legacy-provider
      - name: Check directory
        run: ls -a
      - name: Install all packages listed in a package.json file
        run: npm install
      - name: Run tests listed in App.test.js
        run: npm test
      - name: Run the start script defined in the package.json file
        run: npm start
