# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Digital-Clock with React-App

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Check directory
        working-directory: ./digital-clock-with-React
        run: ls -a
      - name: solve ssl-problem
        working-directory: ./digital-clock-with-React
        run: export NODE_OPTIONS=--openssl-legacy-provider
      - name: Check directory
        working-directory: ./digital-clock-with-React
        run: ls -a
      - name: npm run
        working-directory: ./digital-clock-with-React
        run: npm start
      - name: Check directory
        working-directory: ./digital-clock-with-React
        run: ls -a
